accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("profile/", views.profile, name="profile"),
    path("<int:pk>/detail_update/", views.detail_update, name="detail_update"),
]

pjt_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
  star_grade = (
    ('1','★'),
    ('2','★★'),
    ('3','★★★'),
    ('4','★★★★'),
    ('5','★★★★★'),
  )

  title = models.CharField(max_length=100)
  content = models.TextField()
  movie_name = models.CharField(max_length=100)
  grade = models.CharField(max_length=1, choices=star_grade)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = [
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "email",
        ]


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ["username", "email"]

reviews/forms.py
from .models import Review
from django import forms

class ReviewForm(forms.ModelForm):
  class Meta:
    model = Review
    fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout as auth_logout
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.


@login_required
def index(request):
    if request.user.is_superuser:
        users = User.objects.all()
        context = {"users": users}
        return render(request, "accounts/index.html", context)
    else:
        return redirect("reviews:index")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


@login_required
def detail(request, pk):
    if request.user.is_superuser:
        user_detail = User.objects.get(pk=pk)
        context = {
            "user_detail": user_detail,
        }
        return render(request, "accounts/detail.html", context)
    else:
        return redirect("reviews:index")


@login_required
def detail_update(request, pk):
    if request.user.is_superuser:
        user = User.objects.get(pk=pk)
        if request.method == "POST":
            form = CustomUserChangeForm(request.POST, instance=user)
            if form.is_valid():
                form.save()
                return redirect("accounts:detail", user.pk)
        else:
            form = CustomUserChangeForm(instance=user)
        context = {
            "form": form,
        }
        return render(request, "accounts/detail_update.html", context)
    else:
        return redirect("reviews:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect("reviews:index")


@login_required
def profile(request):
    profile = User.objects.get(pk=request.user.pk)
    context = {
        "profile": profile,
    }
    return render(request, "accounts/profile.html", context)

reviews/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm
from .models import Review
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {"reviews": Review.objects.all()}
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        create_form = ReviewForm(request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect("reviews:index")
    else:
        create_form = ReviewForm()
    context = {
        "create_form": create_form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, pk):
    context = {
        "review": Review.objects.get(pk=pk),
    }
    return render(request, "reviews/detail.html", context)


def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        update_form = ReviewForm(request.POST, instance=review)
        if update_form.is_valid():
            update_form.save()
            return redirect("reviews:detail", review.pk)
    else:
        update_form = ReviewForm(instance=review)
    context = {
        "update_form": update_form,
        "num": review.pk,
    }
    return render(request, "reviews/update.html", context)


def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect("reviews:index")

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container">
    <h1>비밀번호 변경</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn" type="submit">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}detail{% endblock title %}
{% block content %}
  <div class="container">
    <h1>상세정보</h1>
    <hr>
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">NO</th>
            <th scope="col">ID</th>
            <th scope="col">JOIN</th>
            <th scope="col">UPDATE</th>
            <th scope="col">DLELETE</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>{{user_detail.id}}</th>
            <td>{{user_detail.username}}</td>
            <td>{{user_detail.date_joined}}</td>
            <td>
              <a class="btn btn-success" href="{% url 'accounts:detail_update' user_detail.pk %}">수정</a>
            </td>
            <td>
              <a class="btn btn-danger" href="{% url 'accounts:delete' user_detail.pk %}">삭제</a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/detail_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class="text-center my-3">UPDATE</h1>
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="container">
        <button type='submit' class="btn border">OK</button>
      </div>
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block title %}index{% endblock title %}
{% block content %}

  <div class="container mt-5 px-5">
    <h3 class="text-center mb-3">회원목록</h3>
    <div class="row justify-content-center">
      {% for user in users %}
        <div class="col-6 my-3">
          <div class="container border h-100 py-5 text-center">
            <h3 class="my-3">NO.
              {{user.id}}</h3>
            <h3 class="my-3">ID :
              {{user.username}}</h3>
            <hr>
            <a class="btn fw-bolder border border-dark" href="{% url 'accounts:detail' user.id %}">상세정보</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}login{% endblock title %}
{% block content %}
  <div class="container my-4">
    <h1>LOGIN</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form%}
      <input type="submit" value="로그인">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}profile{% endblock title %}
{% block content %}

  <div class="container my-5">
    <div class="card mb-3">
      <div class="card-header">
        <h3 class="fw-bolder">{{profile.username}}님의 프로필</h3>
      </div>
      <div class="card-body">
        <h4 class="card-title fw-bold">이름 :
          {{profile.last_name}}{{profile.first_name}}</h4>
        <hr class="mt-3">
        <p class="card-text fw-bold">이메일 :
          {{profile.email}}</p>
        <p class="card-text fw-bold">가입일자 :
          {{profile.date_joined}}</p>
      </div>
    </div>
    <a class="btn btn-success me-2" href="{% url 'accounts:update' %}">수정</a>
    <a class="btn btn-danger me-2" href="{% url 'accounts:delete' profile.pk %}">삭제</a>
  </div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}signup{% endblock title %}
{% block content %}
  <div class="container">
    <h1 class="my-4">SIGNUP</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class="text-center my-3">UPDATE</h1>
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="container">
        <a class="btn border" href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
        <button type='submit' class="btn border">OK</button>
      </div>
    </form>
  </div>
{% endblock %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}리뷰 작성{% endblock title %}

{% block content %}
<section class="container my-5">
  <h1 class="text-center fw-bold mb-4">리뷰 작성</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form create_form %}
    <input class="btn btn-outline-success" type="submit" value="제출하기">
  </form>
</section>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}리뷰 |
  {{ review.title }}
{% endblock title %}

{% block content %}
  <section class="banner banner-detail">
    <div class="overlay-banner"></div>
    <h1 class="review-title">Review</h1>
  </section>
  <section class="main container my-5">
    <h1 class="text-center fw-bold mb-4">{{ review.title }}</h1>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">영화 :
          {{ review.movie_name }}</h3>
        <h3 class="card-subtitle mb-2">리뷰 :
          {{ review.title }}</h3>
        <h4 class="card-text text-muted">{{ review.created_at }}
          |
          {{ review.updated_at }}</h4>
        <h4 class="card-text">점수 :
          {{ review.get_grade_display }}</h4>
        <h4 class="card-text mt-3 text-bold">내용</h4>
        <h4 class="card-text">{{ review.content }}</h4>
      </div>
    </div>
    <div class="buttons mt-3">
      <a class="btn btn-outline-danger" href="{% url 'reviews:update' review.pk %}" role="button">수정</a>
      <a class="btn btn-outline-danger" href="{% url 'reviews:delete' review.pk %}" role="button">삭제하기</a>
      <a class="btn btn-outline-primary" href="{% url 'reviews:index' %}" role="button">뒤로가기</a>
    </div>
  </section>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}리뷰 목록{% endblock title %}

{% block content %}
  <section class="banner banner-index">
    <div class="overlay-banner"></div>
    <h1 class="review-title">리뷰 목록</h1>
  </section>
  <section class="main container my-5">

    <a class="btn btn-outline-secondary" href="{% url 'reviews:create' %}" role="button">리뷰 작성</a>
    <table class="table text-center">
      <thead>
        <tr>
          <th scope="col">리뷰 제목</th>
          <th scope="col">영화 이름</th>
          <th scope="col">더 보기</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for review in reviews %}
          <tr>
            <td>{{ review.title }}</td>
            <td>{{ review.movie_name }}</td>
            <td>
              <a class="btn btn-outline-secondary" href="{% url 'reviews:detail' review.pk %}" role="button">더보기</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}리뷰 작성{% endblock title %}

{% block content %}
<section class="container my-5">
  <h1 class="text-center fw-bold mb-4">리뷰 작성</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form update_form %}
    <input class="btn btn-outline-success" type="submit" value="제출하기">
  </form>
  <div class="buttons mt-3">
    <a class="btn btn-outline-primary" href="{% url 'reviews:detail' num %}" role="button">뒤로가기</a>
  </div>
</section>
{% endblock content %}

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <img src="{% static '/images/Movie.jpg' %}" alt="" style="height: auto; width: 80px;">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reviews:create' %}">리뷰작성</a>
            </li>
            {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:index' %}">회원목록</a>
              </li>
            {% endif %}
          </ul>
          {% if request.user.is_authenticated %}
            <p class="mb-0 me-3">{{request.user.username}}</p>
            <a class="btn " href="{% url 'accounts:profile' %}" role="button">회원정보</a>
            <a class="btn " href="{% url 'accounts:logout' %}" role="button">로그아웃</a>
          {% else %}
            <a class="btn  me-3" href="{% url 'accounts:login' %}" role="button">로그인</a>
            <a class="btn " href="{% url 'accounts:signup' %}" role="button">회원가입</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}{% endblock content %}
  </body>

</html>